export interface SpriteDef {
  map: string[];
  palette: Record<string, string | null>;
}

export type IconName =
  | "computer"
  | "folder"
  | "key"
  | "user"
  | "chart"
  | "log"
  | "door"
  | "clock"
  | "gear"
  | "power"
  | "star";

export const ICONS: Record<IconName, SpriteDef> = {
  computer: {
    palette: {
      ".": null,
      k: "#000",
      g: "#808080",
      w: "#fff",
      b: "#c0c0c0",
      s: "#000080",
      y: "#fcfc54",
    },
    map: [
      "................",
      "..kkkkkkkkkkkk..",
      "..kbbbbbbbbbbk..",
      "..kbssssssssbk..",
      "..kbsywwwwsybk..",
      "..kbsywsswsybk..",
      "..kbsywssswsbk..",
      "..kbswwwwwwsbk..",
      "..kbssssssssbk..",
      "..kbbbbbbbbbbk..",
      "..kkkkkkkkkkkk..",
      "...kgggggggggk..",
      "..kkkkkkkkkkkk..",
      ".kbbbbbbbbbbbbk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  folder: {
    palette: {
      ".": null,
      k: "#000",
      y: "#fcfc54",
      g: "#bdbd00",
      w: "#fff",
    },
    map: [
      "................",
      "................",
      "..kkk...........",
      ".kyyyk..........",
      "kyywyykkkkkkkkk.",
      "kyyyyyyyyyyyyyk.",
      "kywywywywywywyk.",
      "kyyyyyyyyyyyyyk.",
      "kywywywywywywyk.",
      "kyyyyyyyyyyyyyk.",
      "kywywywywywywyk.",
      "kgggggggggggggk.",
      ".kkkkkkkkkkkkk..",
      "................",
      "................",
      "................",
    ],
  },
  key: {
    palette: { ".": null, k: "#000", y: "#fcfc54", o: "#bdbd00" },
    map: [
      "................",
      "......kkkk......",
      "....kkyyyyk.....",
      "...kyyokkyyk....",
      "...kyok..kykk...",
      "...kyok..kykk...",
      "...kyyokkyyk....",
      "....kkyyyyk.....",
      "......kykk......",
      "......kykk......",
      "......kykk......",
      "......kyykk.....",
      "......kykkk.....",
      "......kyk.......",
      "......kkk.......",
      "................",
    ],
  },
  user: {
    palette: {
      ".": null,
      k: "#000",
      s: "#fcb98e",
      h: "#5a3a1a",
      b: "#000080",
      w: "#fff",
    },
    map: [
      "................",
      "......kkkk......",
      ".....khhhhk.....",
      "....khhhhhhk....",
      "....khsssshk....",
      "....kshhhhsk....",
      "....kssksskk....",
      "....kssssssk....",
      ".....kssssk.....",
      "....kksssskk....",
      "...kbbskskbbk...",
      "..kbbbskskbbbk..",
      "..kbbbbsbbbbbk..",
      "..kbbbbbbbbbbk..",
      "..kbbkkkkkbbbk..",
      "..kkk.....kkk...",
    ],
  },
  chart: {
    palette: {
      ".": null,
      k: "#000",
      b: "#0000c0",
      r: "#c81e1e",
      g: "#008000",
      w: "#fff",
    },
    map: [
      "................",
      ".k.............k",
      ".k............kk",
      ".k............kk",
      ".k.....rr.....kk",
      ".k.....rr..gg.kk",
      ".k.....rr..gg.kk",
      ".k.bb..rr..gg.kk",
      ".k.bb..rr..gg.kk",
      ".k.bb..rr..gg.kk",
      ".k.bb..rr..gg.kk",
      ".k.bb..rr..gg.kk",
      ".kkkkkkkkkkkkkkk",
      ".kkkkkkkkkkkkkkk",
      "................",
      "................",
    ],
  },
  log: {
    palette: {
      ".": null,
      k: "#000",
      w: "#fff",
      b: "#000080",
      y: "#fcfc54",
    },
    map: [
      "................",
      "..kkkkkkkkkkkk..",
      "..kbbbbbbbbbbk..",
      "..kbwwwwwwwwbk..",
      "..kbwkkkkkwwbk..",
      "..kbwwwwwwwwbk..",
      "..kbwkkkkkwwbk..",
      "..kbwwwwwwwwbk..",
      "..kbwkkkkkwwbk..",
      "..kbwwwwwwwwbk..",
      "..kbwkkkkkwwbk..",
      "..kbwwwwwwwwbk..",
      "..kbbbbbbbbbbk..",
      "..kkkkkkkkkkkk..",
      "................",
      "................",
    ],
  },
  door: {
    palette: {
      ".": null,
      k: "#000",
      b: "#5a3a1a",
      d: "#3a2410",
      y: "#fcfc54",
    },
    map: [
      "................",
      "...kkkkkkkkkk...",
      "...kbbbbbbbbk...",
      "...kbdbdbdbbk...",
      "...kbbbbbbbbk...",
      "...kbdbdbdbbk...",
      "...kbbbbbbbbk...",
      "...kbdbdbybbk...",
      "...kbbbbbybbk...",
      "...kbdbdbdbbk...",
      "...kbbbbbbbbk...",
      "...kbdbdbdbbk...",
      "...kbbbbbbbbk...",
      "...kbdbdbdbbk...",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  clock: {
    palette: {
      ".": null,
      k: "#000",
      w: "#fff",
      g: "#c0c0c0",
      r: "#c81e1e",
    },
    map: [
      "................",
      "......kkkk......",
      "....kkggggkk....",
      "...kgwwwwwwgk...",
      "...kwwkwwwwwk...",
      "..kgwwkwwwwwgk..",
      "..kgwwkwwwwwgk..",
      "..kgwwkkkrrwgk..",
      "..kgwwwwwrwwgk..",
      "..kgwwwwwwwwgk..",
      "..kgwwwwwwwwgk..",
      "...kwwwwwwwwk...",
      "...kgwwwwwwgk...",
      "....kkggggkk....",
      "......kkkk......",
      "................",
    ],
  },
  gear: {
    palette: { ".": null, k: "#000", g: "#808080", w: "#c0c0c0" },
    map: [
      "................",
      "......kkkk......",
      "......kwwk......",
      "..kkk.kwwk.kkk..",
      "..kwkkkwwkkkwk..",
      "...kwwkwwkwwk...",
      "....kwwwwwwk....",
      "..kkkwwkkwwkkk..",
      "..kwwwkkkkwwwk..",
      "..kkkwwkkwwkkk..",
      "....kwwwwwwk....",
      "...kwwkwwkwwk...",
      "..kwkkkwwkkkwk..",
      "..kkk.kwwk.kkk..",
      "......kwwk......",
      "......kkkk......",
    ],
  },
  power: {
    palette: { ".": null, k: "#000", r: "#c81e1e", w: "#fff" },
    map: [
      "................",
      "................",
      "......kkkk......",
      "....kkkkkkkk....",
      "...kkrrkkrrkk...",
      "..kkrrkkkkrrkk..",
      "..krrkk..kkrrk..",
      "..krrk....krrk..",
      "..krrk....krrk..",
      "..krrkk..kkrrk..",
      "..kkrrkkkkrrkk..",
      "...kkrrkkrrkk...",
      "....kkkkkkkk....",
      "......kkkk......",
      "................",
      "................",
    ],
  },
  star: {
    palette: { ".": null, k: "#000", y: "#fcfc54", o: "#bdbd00" },
    map: [
      "................",
      ".......kk.......",
      ".......kyk......",
      "......kyyk......",
      "......kyok......",
      "kkkkkkkyyokkkkkk",
      ".kyyyyyyyyyyyok.",
      "..kyyyyyyyyyok..",
      "...kyyyyyyyok...",
      "....kyyyyyok....",
      "...kyyyyyyyok...",
      "...kykyyyykyk...",
      "..kkkkkkokkkkk..",
      "................",
      "................",
      "................",
    ],
  },
};
