"""0001 initial schema

Revision ID: 6853668a5e90
Revises: 
Create Date: 2026-04-27 15:43:28.329042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6853668a5e90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', name='user_role'), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index('cards_active_idx', 'cards', ['active'], unique=False, postgresql_where=sa.text('active = TRUE'))
    op.create_index('cards_user_id_idx', 'cards', ['user_id'], unique=False)
    op.create_table('access_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('access_logs_occurred_at_idx', 'access_logs', [sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('access_logs_uid_occurred_idx', 'access_logs', ['uid', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('access_logs_user_id_occurred_idx', 'access_logs', ['user_id', sa.literal_column('occurred_at DESC')], unique=False)
    # ### end Alembic commands ###

    # updated_at 자동 갱신 트리거 (database.md 스펙)
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
        BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    """)
    op.execute("""
        CREATE TRIGGER cards_set_updated_at BEFORE UPDATE ON cards
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS cards_set_updated_at ON cards;")
    op.execute("DROP TRIGGER IF EXISTS users_set_updated_at ON users;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('access_logs_user_id_occurred_idx', table_name='access_logs')
    op.drop_index('access_logs_uid_occurred_idx', table_name='access_logs')
    op.drop_index('access_logs_occurred_at_idx', table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index('cards_user_id_idx', table_name='cards')
    op.drop_index('cards_active_idx', table_name='cards', postgresql_where=sa.text('active = TRUE'))
    op.drop_table('cards')
    op.drop_table('users')
    op.execute("DROP TYPE IF EXISTS user_role;")
    # ### end Alembic commands ###
